-- Bootstrap club — REMOVED in the multi-club model (issue 29).
-- v1 seeded a single default club here so `clubId()` (`select id from club limit 1`)
-- had something to work with. With real multi-club, clubs are created by an
-- authenticated organizer through /admin (and the dev environment seeds an example
-- club + membership in seed.sql). This migration is intentionally a no-op so the
-- migration history stays continuous on a `db reset`.
